import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { AppThemeProvider } from "./providers/themeProvider";
import ToastProvider from "./providers/toastProvider";
import { ClerkProvider } from "@clerk/nextjs";
import ReduxProvider from "./providers/reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <AppThemeProvider>
            <ToastProvider>
              <ReduxProvider>{children}</ReduxProvider>
            </ToastProvider>
          </AppThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
